language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.1"
  - "1.3"
  - "1.5"
  - "1.7"
  - "2.0"
  - "2.1"
  - "2.3"
  - "2.5"
  - "3.0"
  - "3.1"
  - "3.3"
  - "iojs"
notifications:
  email:
    on_success: never
script: "npm run-script test-cov"
after_script: "cat ./coverage/lcov.info | coveralls"
