environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "1.1"
    - nodejs_version: "1.3"
    - nodejs_version: "1.5"
    - nodejs_version: "1.7"
    - nodejs_version: "2.0"
    - nodejs_version: "2.1"
    - nodejs_version: "2.3"
    - nodejs_version: "2.5"
    - nodejs_version: "3.0"
    - nodejs_version: "3.1"
    - nodejs_version: "3.3"
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
